### ISSUE TITLE
Add more details to Read-the-Docs Documentation

### ISSUE THREAD

**Issue by jzbbrv-hpi** [DILiS-lab/SimbaML#5]
Issue was opened to provide more sophisticated documentation for SimbaML and make it ready to publish.

To-Dos:
[ ] Move example to Quickstart
[ ] Add Installation to landing page of read-the-docs
[ ] remove example from GitHub and add link to documentation instead
[ ] Include link to paper

**Comment by MaximilianKleissl** [comment]
Please provide a detailed description.

**Comment by MaximilianKleissl** [comment]
Please provide a detailed description.

**Comment by jzbbrv-hpi** [comment]
Can this issue be closed with #6 being merged?

**Comment by MaximilianKleissl** [comment]
I think, that this is up to you, as you created that issue.
